name: Publish

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches: 
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish